-- ==============================================================================
-- Phase 1: Snowflake Infrastructure Setup
-- ==============================================================================
-- Note: Make sure you are using the ACCOUNTADMIN role when running this script
USE ROLE ACCOUNTADMIN;

-- 1. Create the Resource Monitor (The Security Guard)
-- This ensures you never accidentally spend more than 10 credits a month.
CREATE OR REPLACE RESOURCE MONITOR hazardwatch_monitor
  WITH
    CREDIT_QUOTA = 10
    FREQUENCY    = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
      ON 50  PERCENT DO NOTIFY
      ON 80  PERCENT DO NOTIFY
      ON 100 PERCENT DO SUSPEND;

-- 2. Create the Warehouse (The Engine)
-- X-Small size, auto-suspends after 60 seconds to save money, and is tied to the monitor above.
CREATE OR REPLACE WAREHOUSE HAZARDWATCH_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
       AUTO_SUSPEND = 60
       AUTO_RESUME = TRUE
       RESOURCE_MONITOR = hazardwatch_monitor;

-- 3. Create the Database and Schemas (The Filing Cabinets)
CREATE OR REPLACE DATABASE HAZARDWATCH_DB;

CREATE OR REPLACE SCHEMA HAZARDWATCH_DB.RAW_SCHEMA;
CREATE OR REPLACE SCHEMA HAZARDWATCH_DB.BRONZE_SCHEMA;
CREATE OR REPLACE SCHEMA HAZARDWATCH_DB.SILVER_SCHEMA;
CREATE OR REPLACE SCHEMA HAZARDWATCH_DB.GOLD_SCHEMA;
CREATE OR REPLACE SCHEMA HAZARDWATCH_DB.AUDIT_SCHEMA;

-- 4. Create the Roles (The Security Badges)
CREATE OR REPLACE ROLE HAZARDWATCH_ADMIN;
CREATE OR REPLACE ROLE HAZARDWATCH_READER;
CREATE OR REPLACE ROLE HAZARDWATCH_INGEST;

-- Grant the Admin role access to everything
GRANT ALL PRIVILEGES ON DATABASE HAZARDWATCH_DB TO ROLE HAZARDWATCH_ADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE HAZARDWATCH_DB TO ROLE HAZARDWATCH_ADMIN;
GRANT USAGE, OPERATE ON WAREHOUSE HAZARDWATCH_WH TO ROLE HAZARDWATCH_ADMIN;

-- Ensure Admin can always read tables created by other roles (like ACCOUNTADMIN in Snowpipe)
GRANT SELECT ON ALL TABLES IN SCHEMA HAZARDWATCH_DB.RAW_SCHEMA TO ROLE HAZARDWATCH_ADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HAZARDWATCH_DB.RAW_SCHEMA TO ROLE HAZARDWATCH_ADMIN;

-- Grant the Reader role (Superset) access ONLY to the Gold Schema
GRANT USAGE ON DATABASE HAZARDWATCH_DB TO ROLE HAZARDWATCH_READER;
GRANT USAGE ON SCHEMA HAZARDWATCH_DB.GOLD_SCHEMA TO ROLE HAZARDWATCH_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA HAZARDWATCH_DB.GOLD_SCHEMA TO ROLE HAZARDWATCH_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HAZARDWATCH_DB.GOLD_SCHEMA TO ROLE HAZARDWATCH_READER;
GRANT USAGE ON WAREHOUSE HAZARDWATCH_WH TO ROLE HAZARDWATCH_READER;

-- Grant all roles to the all-powerful SYSADMIN so you can manage them in the UI easily
GRANT ROLE HAZARDWATCH_ADMIN TO ROLE SYSADMIN;
GRANT ROLE HAZARDWATCH_READER TO ROLE SYSADMIN;
GRANT ROLE HAZARDWATCH_INGEST TO ROLE SYSADMIN;

-- Finally, give YOUR user account the Admin badge
-- (e.g. GRANT ROLE HAZARDWATCH_ADMIN TO USER JSMITH;)
GRANT ROLE HAZARDWATCH_ADMIN TO USER VENKATSAI9912;
